# Generated by Django 4.1.4 on 2022-12-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=1000)),
                ('timefrom', models.CharField(max_length=100)),
                ('timeto', models.CharField(max_length=100)),
            ],
        ),
    ]
